import React from "react";
import Link from "next/link";

export default function NotFound() {
  return (
    <div style={{
      background: "#ECEFF1",
      color: "rgba(0,0,0,0.87)",
      fontFamily: "Roboto, Helvetica, Arial, sans-serif",
      margin: 0,
      padding: "0",
      minHeight: "100vh",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      paddingTop: "100px"
    }}>
      <div style={{
        background: "white",
        maxWidth: "360px",
        padding: "32px 24px 16px",
        borderRadius: "3px",
        boxShadow: "0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)",
      }}>
        <h2 style={{
          color: "#ffa100",
          fontWeight: "bold",
          fontSize: "16px",
          margin: "0 0 8px"
        }}>404</h2>
        <h1 style={{
          fontSize: "22px",
          fontWeight: 300,
          color: "rgba(0,0,0,0.6)",
          margin: "0 0 16px"
        }}>Page Not Found</h1>
        <p style={{
          lineHeight: "140%",
          margin: "16px 0 24px",
          fontSize: "14px"
        }}>
          The specified file was not found on this website. Please check the URL for mistakes and try again.
        </p>
        <h3 style={{
          color: "#888",
          fontWeight: "normal",
          fontSize: "16px",
          margin: "16px 0 12px"
        }}>Why am I seeing this?</h3>
        <p style={{
          lineHeight: "140%",
          margin: "16px 0 24px",
          fontSize: "14px"
        }}>
          This page was generated by the Firebase Command-Line Interface. To modify it, edit the <code>404.html</code> file in your project's configured <code>public</code> directory.
        </p>
      </div>
    </div>
  );
}
